apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-stable
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: helm-stable-only
  revisionHistoryLimit: 2

  source:
    repoURL: 'https://kubernetes-charts.storage.googleapis.com'
    targetRevision: 1.9.17
    path: ''
    chart: jenkins

  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: helm-stable-only

  # Sync policy
  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).